<?php
declare(strict_types=1);
require_once __DIR__ . '/functions.php';
$user=require_auth();$pageTitle='Личный кабинет';$active='account';$pdo=db();
if(is_post()&&isset($_FILES['photo'])){
    verify_csrf();$orderId=(int)($_POST['order_id']??0);$file=$_FILES['photo'];$errors=[];
    if(($file['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK)$errors[]='Выберите файл для загрузки.';
    if(($file['size']??0)>5*1024*1024)$errors[]='Размер файла не должен превышать 5 МБ.';
    $allowed=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'];$mime='';
    if(!$errors){$mime=(new finfo(FILEINFO_MIME_TYPE))->file($file['tmp_name']);if(!isset($allowed[$mime]))$errors[]='Разрешены изображения JPG, PNG и WebP.';}
    if($pdo&&!$errors){$s=$pdo->prepare('SELECT id FROM orders WHERE id=? AND user_id=?');$s->execute([$orderId,$user['id']]);if(!$s->fetch())$errors[]='Заказ не найден или принадлежит другому пользователю.';}
    if(!$errors){$dir=__DIR__.'/uploads';if(!is_dir($dir))mkdir($dir,0775,true);$name=bin2hex(random_bytes(12)).'.'.$allowed[$mime];if(!move_uploaded_file($file['tmp_name'],$dir.'/'.$name))$errors[]='Не удалось сохранить файл.';elseif($pdo){$s=$pdo->prepare('INSERT INTO photos(user_id,order_id,file_name,original_name,mime_type) VALUES(?,?,?,?,?)');$s->execute([$user['id'],$orderId,$name,basename((string)$file['name']),$mime]);}}
    flash($errors?'error':'success',$errors?implode(' ',$errors):'Фотография добавлена в личный кабинет.');redirect('account.php');
}
$orders=[];$photos=[];
if($pdo){$s=$pdo->prepare('SELECT o.*,p.name AS program_name,a.character_name FROM orders o JOIN programs p ON p.id=o.program_id LEFT JOIN animators a ON a.id=o.animator_id WHERE o.user_id=? ORDER BY o.event_date DESC');$s->execute([$user['id']]);$orders=$s->fetchAll();$s=$pdo->prepare('SELECT ph.*,o.event_date,p.name AS program_name FROM photos ph JOIN orders o ON o.id=ph.order_id JOIN programs p ON p.id=o.program_id WHERE ph.user_id=? ORDER BY ph.uploaded_at DESC');$s->execute([$user['id']]);$photos=$s->fetchAll();}
if(!$orders&&($user['role']??'')!=='admin')$orders=[['id'=>15,'program_name'=>'Аркадный квест','character_name'=>'Фред','event_date'=>'2026-09-15','event_time'=>'16:00:00','address'=>'Москва, ул. Праздничная, 12','total_price'=>7900,'status'=>'confirmed']];
require __DIR__ . '/partials/header.php';
?>
<section class="section"><div class="container"><span class="eyebrow">Мои заказы и фотографии</span><h1 class="section-title">ЛИЧНЫЙ КАБИНЕТ</h1><div class="account-layout" style="margin-top:30px"><aside class="panel profile-card"><span class="bear accent-yellow"><i></i></span><h2><?= e($user['name']) ?></h2><small><?= e($user['email']) ?></small><nav class="profile-menu"><a href="#orders">Мои заказы</a><a href="#photos">Фотографии</a><?php if(($user['role']??'')==='admin'): ?><a href="admin.php">Админ-панель</a><?php endif; ?><a href="logout.php">Выйти</a></nav></aside><div><section class="panel" id="orders"><span class="eyebrow">Ближайшие и завершённые</span><h2>МОИ ЗАКАЗЫ</h2><?php if(!$orders): ?><div class="empty">Заказов пока нет. <a class="eyebrow" href="order.php">Оформить первый</a></div><?php endif; ?><?php foreach($orders as $order): ?><article class="order-row"><div><span class="eyebrow">Заказ №<?= (int)$order['id'] ?></span><h3><?= e($order['program_name']) ?></h3><p><?= e(date('d.m.Y',strtotime($order['event_date']))) ?> · <?= e(substr($order['event_time'],0,5)) ?> · <?= e($order['address']) ?></p><small>Герой: <?= e($order['character_name']??'будет назначен') ?> · Статус: <?= e($order['status']) ?></small></div><strong class="price"><?= format_price((float)$order['total_price']) ?></strong></article><?php endforeach; ?></section><section class="panel" id="photos" style="margin-top:22px"><span class="eyebrow">Материалы мероприятий</span><h2>ФОТОГРАФИИ</h2><div class="gallery"><?php if($photos):foreach($photos as $photo): ?><figure><div class="photo"><?php if(is_file(__DIR__.'/uploads/'.$photo['file_name'])): ?><img src="uploads/<?= e($photo['file_name']) ?>" alt="<?= e($photo['original_name']) ?>"><?php endif; ?></div><figcaption><?= e($photo['program_name']) ?></figcaption></figure><?php endforeach;else: ?><div class="photo"></div><div class="photo" style="filter:hue-rotate(90deg)"></div><div class="photo" style="filter:hue-rotate(180deg)"></div><?php endif; ?></div><?php if($orders): ?><form method="post" enctype="multipart/form-data" style="margin-top:24px"><?= csrf_field() ?><div class="form-grid"><div class="field"><label for="order_id">Заказ</label><select id="order_id" name="order_id" required><?php foreach($orders as $order): ?><option value="<?= (int)$order['id'] ?>">№<?= (int)$order['id'] ?> — <?= e($order['program_name']) ?></option><?php endforeach; ?></select></div><div class="field"><label for="photo">Фото JPG, PNG или WebP, до 5 МБ</label><input id="photo" type="file" name="photo" accept="image/jpeg,image/png,image/webp" required></div></div><div class="form-actions"><button class="button button--cyan">Загрузить фотографию</button></div></form><?php endif; ?></section></div></div></div></section>
<?php require __DIR__ . '/partials/footer.php'; ?>

